<?php
/**
 * © 2026 Neria.software - All rights reserved
 *
 * CertificateManager — Certificats d'authenticité dynamiques
 *
 * Génère un PDF signé (TCPDF + signature manuscrite Neria) et l'envoie
 * au client par email. Déclenchement manuel depuis la fiche commande PS.
 *
 * @author  Neria
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

class CertificateManager
{
    // ── Config keys ───────────────────────────────────────────────
    const CFG_ENABLED       = 'NERIA_CERT_ENABLED';
    const CFG_SERIAL_PREFIX = 'NERIA_CERT_SERIAL_PREFIX';
    const CFG_TITLE         = 'NERIA_CERT_TITLE';
    const CFG_SUBTITLE      = 'NERIA_CERT_SUBTITLE';
    const CFG_BODY          = 'NERIA_CERT_BODY';
    const CFG_QR_ENABLED    = 'NERIA_CERT_QR_ENABLED';
    const CFG_QR_URL        = 'NERIA_CERT_QR_URL';

    const TABLE = 'neria_certificate';

    /** @var \Neria */
    private $module;
    /** @var \Db */
    private $db;
    /** @var int */
    private $idShop;

    public function __construct(\Neria $module)
    {
        $this->module = $module;
        $this->db     = \Db::getInstance();
        $this->idShop = (int) \Context::getContext()->shop->id;
    }

    // ============================================================
    // ÉMISSION D'UN CERTIFICAT
    // ============================================================

    /**
     * Génère le PDF et l'envoie par email au client.
     * Retourne '' si succès, message d'erreur sinon.
     *
     * @param int    $idOrder
     * @param int    $idProduct
     * @param int    $idOrderDetail
     * @param string $serialNumber  Vide = auto-généré
     * @param string $artisanNote   Note libre de l'artisan
     * @param bool   $sendEmail     Envoyer ou juste générer
     */
    public function issue(
        int    $idOrder,
        int    $idProduct,
        int    $idOrderDetail,
        string $serialNumber = '',
        string $artisanNote  = '',
        bool   $sendEmail    = true
    ): string {
        // ── Commande & client ─────────────────────────────────────
        $order = new \Order($idOrder);
        if (!\Validate::isLoadedObject($order)) {
            return AdminTranslator::t('msg.certificate_order_not_found');
        }

        $customer = new \Customer((int) $order->id_customer);
        $customerName = trim($customer->firstname . ' ' . $customer->lastname);
        $customerEmail = $customer->email;

        // ── Langue du client (même algorithme que EmailRenderer pour l'email,
        //    afin que le PDF joint corresponde à la langue de l'email) ──────
        // Résolue AVANT de charger le produit ci-dessous : le nom produit
        // doit être chargé dans CETTE langue, pas celle du contexte BO de
        // l'employé qui déclenche l'émission — sinon un marchand dont le BO
        // est en arabe/chinois mais qui certifie une commande d'un client
        // français voyait "PRODUIT" s'afficher en rectangles vides (police
        // WinAnsi choisie pour $lang='fr' ne sait pas rendre l'arabe/CJK).
        $lang = $this->resolveCertificateLang($order, (int) $customer->id_lang);

        // ── Produit ───────────────────────────────────────────────
        $idLangProduct = (int) (\Language::getIdByIso($lang) ?: \Context::getContext()->language->id);
        $product = new \Product($idProduct, false, $idLangProduct);
        $productName = $product->name ?: 'Produit #' . $idProduct;

        // ── Numéro de série ───────────────────────────────────────
        // Sous accès concurrent (émissions quasi simultanées), MAX(id_certificate)+1
        // peut donner deux fois le même numéro avant que l'un des deux INSERT
        // n'ait posé la contrainte UNIQUE. Si le numéro est auto-généré (pas
        // fourni explicitement par l'appelant), on retente avec un offset
        // croissant plutôt que d'échouer un certificat pourtant légitime.
        $autoGenerated = ($serialNumber === '');
        if ($autoGenerated) {
            $serialNumber = $this->generateSerial();
        }

        if ($this->serialExists($serialNumber)) {
            if (!$autoGenerated) {
                return AdminTranslator::tVars('msg.certificate_serial_exists', ['serial' => $serialNumber]);
            }
            $resolved = false;
            for ($offset = 1; $offset <= 5; $offset++) {
                $candidate = $this->generateSerial($offset);
                if (!$this->serialExists($candidate)) {
                    $serialNumber = $candidate;
                    $resolved     = true;
                    break;
                }
            }
            if (!$resolved) {
                return AdminTranslator::tVars('msg.certificate_serial_exists', ['serial' => $serialNumber]);
            }
        }

        // ── Génère le PDF ─────────────────────────────────────────
        $pdfResult = $this->generatePdf(
            $serialNumber, $order, $customerName, $productName, $artisanNote, $lang
        );
        if (isset($pdfResult['error'])) {
            return $pdfResult['error'];
        }

        $pdfContent = $pdfResult['content'];
        $pdfPath    = $pdfResult['path'];

        // ── Sauvegarde en DB ──────────────────────────────────────
        $inserted = $this->db->insert(self::TABLE, [
            // id_shop de LA COMMANDE, pas $this->idShop (contexte BO de
            // l'employé qui déclenche l'émission) : un employé en contexte
            // "toutes les boutiques" (ou dont le contexte BO courant diffère
            // de la boutique de la commande) émettant un certificat pour une
            // commande d'une AUTRE boutique enregistrait sinon le certificat
            // sous la mauvaise boutique — invisible dans getByOrder()/
            // getAll() de la vraie boutique, polluant les stats de l'autre.
            'id_shop'         => (int) $order->id_shop,
            // Stocké directement (pas seulement dérivable via id_order) :
            // permet à GdprAuditManager::purgeCustomerData() de purger ce
            // certificat même si la commande liée a depuis été supprimée du
            // BO PrestaShop — sans cette colonne, un certificat (nom client
            // en clair) survivait indéfiniment à une demande d'effacement
            // RGPD dès que la commande n'existait plus pour le JOIN.
            'id_customer'     => (int) $order->id_customer,
            'id_order'        => $idOrder,
            'id_product'      => $idProduct,
            'id_order_detail' => $idOrderDetail,
            'serial_number'   => pSQL($serialNumber),
            'customer_name'   => pSQL($customerName),
            'product_name'    => pSQL($productName),
            'artisan_note'    => pSQL($artisanNote),
            'pdf_path'        => pSQL($pdfPath),
            'emailed'         => 0,
            'date_issued'     => date('Y-m-d H:i:s'),
            'date_add'        => date('Y-m-d H:i:s'),
        ]);

        if (!$inserted) {
            // Doublon de clé unique sur serial_number (émissions quasi simultanées)
            // ou autre échec DB — on ne continue jamais avec un id_certificate invalide.
            if (class_exists('WatchdogManager')) {
                (new WatchdogManager($this->module))->warning(
                    'Échec d\'émission de certificat : ' . $serialNumber . ' — ' . $productName
                    . ' (commande #' . $idOrder . ', client : ' . $customerEmail . ')',
                    '', 'CertificateManager'
                );
            }
            return AdminTranslator::t('msg.certificate_save_failed');
        }

        $idCertificate = (int) $this->db->Insert_ID();

        // ── Envoi email ───────────────────────────────────────────
        if ($sendEmail) {
            $err = $this->sendCertificateEmail(
                $customerEmail, $customerName, $productName,
                $serialNumber, $pdfContent, $order, (int) $customer->id_lang
            );
            if ($err !== '') {
                return $err;
            }

            $this->db->update(self::TABLE, ['emailed' => 1],
                '`id_certificate` = ' . $idCertificate);
        }

        // ── Log Watchdog ──────────────────────────────────────────
        if (class_exists('WatchdogManager')) {
            (new WatchdogManager($this->module))->info(
                'Certificat émis : ' . $serialNumber . ' — ' . $productName
                . ' (commande #' . $idOrder . ', client : ' . $customerEmail . ')',
                '', 'CertificateManager'
            );
        }

        return '';
    }

    /**
     * Retélécharge le PDF d'un certificat déjà émis.
     * Retourne le contenu binaire du PDF ou '' si erreur.
     */
    public function redownload(int $idCertificate): array
    {
        // Pas de filtre `id_shop` = $this->idShop (contexte BO courant de
        // l'employé) : ce bouton est posté depuis la fiche commande PS
        // (order_certificate_block.tpl → action sur AdminModules&configure=
        // neria), dont le contexte de boutique en tête de BO peut très bien
        // différer de celle de LA COMMANDE affichée (cas normal en
        // multi-boutique tant que l'employé n'a pas explicitement changé de
        // sélecteur). id_certificate est déjà une clé globalement unique
        // (comme id_order pour getByOrder() ci-dessous) — y ajouter ce
        // filtre ne fait que réintroduire, pour le téléchargement, l'exacte
        // "invisibilité inter-boutique" qu'issue() documente déjà avoir
        // corrigée pour l'écriture (id_shop DE LA COMMANDE, pas $this->idShop).
        $row = $this->db->getRow(
            'SELECT * FROM `' . _DB_PREFIX_ . self::TABLE . '`
             WHERE `id_certificate` = ' . $idCertificate
        );
        if (!$row) {
            return ['error' => AdminTranslator::t('msg.certificate_not_found')];
        }

        $order    = new \Order((int) $row['id_order']);
        $customer = new \Customer((int) $order->id_customer);
        $lang     = $this->resolveCertificateLang($order, (int) $customer->id_lang);
        $result   = $this->generatePdf(
            $row['serial_number'],
            $order,
            $row['customer_name'],
            $row['product_name'],
            $row['artisan_note'] ?? '',
            $lang
        );
        return $result;
    }

    // ============================================================
    // GÉNÉRATION PDF
    // ============================================================

    /**
     * Résout la langue à utiliser pour le PDF ET l'email du certificat, avec
     * le même algorithme que EmailRenderer (TranslationEngine::resolveOptimalLang) :
     * compte client si boutique multi-langues, sinon pays de facturation.
     * Garantit que le PDF joint est dans la même langue que l'email qui
     * l'accompagne (EmailRenderer applique indépendamment le même algorithme
     * sur les mêmes données de commande/client).
     */
    private function resolveCertificateLang(\Order $order, int $idLang): string
    {
        $engine = new \TranslationEngine($this->module);

        // Round 158 : quand NERIA_AUTO_LANG est désactivé, EmailRenderer::
        // resolveEmailLang() court-circuite entièrement l'algorithme pays/
        // code-postal et retombe sur la langue brute du compte client
        // (langFromId($idLang)) — cette méthode ne le faisait jamais et
        // appliquait TOUJOURS l'algorithme pays, cassant la parité PDF/email
        // que le commentaire de classe ci-dessus annonce pourtant garantir :
        // un client dont le compte est en langue A mais dont l'adresse de
        // facturation est dans un pays de langue B recevait un PDF en B et
        // un email en A dès que le marchand désactivait la détection auto.
        if (class_exists('ConfigManager') && !(new \ConfigManager($this->module))->isAutoLangEnabled()) {
            return $engine->langFromId($idLang);
        }

        $countryIso = '';
        $postcode   = '';
        if ($order->id_address_invoice) {
            $address = new \Address((int) $order->id_address_invoice);
            if (\Validate::isLoadedObject($address)) {
                $countryIso = (string) (\Country::getIsoById((int) $address->id_country) ?: '');
                $postcode   = (string) $address->postcode;
            }
        }

        return $engine->resolveOptimalLang($idLang, $countryIso, $postcode);
    }

    /**
     * Choisit les polices TCPDF adaptées au script de la langue. Les
     * polices core (helvetica/times) sont limitées à l'encodage WinAnsi :
     * arabe, CJK et cyrillique s'y affichent en rectangles vides. Les
     * polices ci-dessous sont fournies avec TCPDF (fonts/*.php), aucun
     * fichier ni dépendance à ajouter au module.
     *
     * @return array{0: string, 1: string, 2: bool} [$fontSans, $fontSerif, $isRtl]
     */
    private function pdfFontsForLang(string $lang): array
    {
        switch ($lang) {
            case 'ar':
                // Police arabe (script RTL) — un seul style disponible,
                // voir pdfSetFont() qui ignore B/I pour cette police.
                return ['aealarabiya', 'aealarabiya', true];
            case 'zh':
                return ['cid0cs', 'cid0cs', false]; // chinois simplifié
            case 'tw':
                return ['cid0ct', 'cid0ct', false]; // chinois traditionnel
            case 'ja':
                return ['cid0jp', 'cid0jp', false];
            case 'ko':
                return ['cid0kr', 'cid0kr', false];
            case 'ru':
                // Cyrillique : dejavusans (styles complets) + freeserif
                return ['dejavusans', 'freeserif', false];
            default:
                return ['helvetica', 'times', false];
        }
    }

    /**
     * Applique une police/taille en tenant compte des polices non-Latin
     * (aealarabiya, cid0*) qui ne fournissent qu'un seul style TCPDF —
     * demander 'B' ou 'I' sur ces polices lève une erreur TCPDF.
     */
    private function pdfSetFont(\TCPDF $pdf, string $family, string $style, int $size): void
    {
        $singleStyleFamilies = ['aealarabiya', 'cid0cs', 'cid0ct', 'cid0jp', 'cid0kr'];
        if (in_array($family, $singleStyleFamilies, true)) {
            $style = '';
        }
        $pdf->SetFont($family, $style, $size);
    }

    private function generatePdf(
        string $serial,
        \Order $order,
        string $customerName,
        string $productName,
        string $artisanNote,
        string $lang
    ): array {
        $tcpdfPath = _PS_ROOT_DIR_ . '/vendor/tecnickcom/tcpdf/tcpdf.php';
        if (!file_exists($tcpdfPath)) {
            return ['error' => AdminTranslator::t('msg.certificate_tcpdf_missing')];
        }
        require_once $tcpdfPath;

        // Configuration::get(..., (int) $order->id_shop) : round 106, le nom
        // de boutique imprimé sur le PDF ignorait la boutique réelle de LA
        // COMMANDE — même piège déjà corrigé pour {shop_url} plus bas dans
        // cette même méthode (bascule temporaire de Context::shop), mais qui
        // ne couvrait pas ce $shopName-ci, résolu AVANT la bascule.
        $shopName   = (string) \Configuration::get('PS_SHOP_NAME', null, null, (int) $order->id_shop);
        $shopDomain = \Tools::getShopDomainSsl(true);
        $dateStr    = \NeriaTools::formatDate($order->date_add, $lang);
        $issuedStr  = \NeriaTools::formatDate('now', $lang);

        // Instancié ici (et non plus seulement plus bas pour les libellés du
        // tableau) car les valeurs PAR DÉFAUT du titre/sous-titre/corps
        // doivent elles aussi être traduites — auparavant codées en dur en
        // français, elles s'affichaient dans cette langue quelle que soit
        // celle du client tant que le marchand n'avait pas personnalisé ces
        // 3 champs en configuration.
        $engine = new \TranslationEngine($this->module);

        $title    = (string) \Configuration::get(self::CFG_TITLE)    ?: $engine->get('certificate_email', 'certificate_pdf_default_title', $lang);
        $subtitle = (string) \Configuration::get(self::CFG_SUBTITLE) ?: $engine->get('certificate_email', 'certificate_pdf_default_subtitle', $lang);
        $bodyText = (string) \Configuration::get(self::CFG_BODY)     ?: $engine->get('certificate_email', 'certificate_pdf_default_body', $lang);

        // Substitution de {shop_name} même lorsque le marchand a personnalisé
        // ces champs — auparavant seule la valeur par défaut (fallback) était
        // interpolée, une valeur configurée manuellement affichait la variable
        // brute non résolue.
        $pdfVars  = ['{shop_name}' => $shopName];
        $title    = strtr($title, $pdfVars);
        $subtitle = strtr($subtitle, $pdfVars);
        $bodyText = strtr($bodyText, $pdfVars);

        $qrEnabled = (bool) \Configuration::get(self::CFG_QR_ENABLED);
        $qrBaseUrl = (string) \Configuration::get(self::CFG_QR_URL) ?: $shopDomain;
        // getShopDomainSsl(true) peut malgré tout retourner du http:// si le
        // SSL n'est pas activé côté PS (PS_SSL_ENABLED) — un QR code sur un
        // certificat imprimé/PDF ne doit jamais pointer vers une URL non
        // chiffrée. cert_qr_url (BO) est déjà validé en https:// à
        // l'enregistrement ; ce garde-fou ne couvre donc que le fallback.
        if (stripos($qrBaseUrl, 'http://') === 0) {
            $qrBaseUrl = 'https://' . substr($qrBaseUrl, 7);
        }

        // Signature manuscrite
        $sigPath  = '';
        $sigRow   = $this->db->getRow(
            'SELECT `image_path` FROM `' . _DB_PREFIX_ . 'neria_signature`
             WHERE `is_active` = 1 AND `id_shop` = ' . $this->idShop . '
             ORDER BY `date_upd` DESC'
        );
        if ($sigRow && !empty($sigRow['image_path'])) {
            $candidate = _PS_MODULE_DIR_ . 'neria/' . ltrim($sigRow['image_path'], '/');
            if (file_exists($candidate)) {
                $sigPath = $candidate;
            }
        }

        // Logo boutique
        $logoPath = '';
        $psLogo   = _PS_IMG_DIR_ . \Configuration::get('PS_LOGO');
        if (file_exists($psLogo)) {
            $logoPath = $psLogo;
        }

        // ── Police adaptée au script de la langue ──────────────────
        // Les polices core TCPDF (helvetica/times) sont limitées à
        // l'encodage WinAnsi : arabe, CJK et cyrillique s'affichent en
        // rectangles vides avec elles. Les polices ci-dessous sont fournies
        // avec TCPDF (aucune dépendance externe) et couvrent ces scripts.
        [$fontSans, $fontSerif, $isRtl] = $this->pdfFontsForLang($lang);

        // ── PDF ───────────────────────────────────────────────────
        try {
            $pdf = new \TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
            $pdf->SetCreator('Neria');
            $pdf->SetAuthor($shopName);
            $pdf->SetTitle($title . ' — ' . $serial);
            $pdf->SetMargins(20, 20, 20);
            $pdf->SetAutoPageBreak(true, 20);
            $pdf->setPrintHeader(false);
            $pdf->setPrintFooter(false);
            $pdf->setRTL($isRtl);
            $pdf->AddPage();

            // ── Fond luxe (rectangle or pâle) ────────────────────
            $pdf->SetFillColor(250, 246, 240);
            $pdf->Rect(10, 10, 190, 277, 'F');

            // ── Bordure dorée ─────────────────────────────────────
            $pdf->SetDrawColor(179, 139, 89);
            $pdf->SetLineWidth(0.8);
            $pdf->Rect(12, 12, 186, 273);
            $pdf->SetLineWidth(0.3);
            $pdf->Rect(14, 14, 182, 269);

            $y = 22;

            // ── Logo ──────────────────────────────────────────────
            if ($logoPath !== '') {
                $pdf->Image($logoPath, 85, $y, 40, 0, '', '', '', false, 300);
                $y += 28;
            } else {
                $this->pdfSetFont($pdf, $fontSans, 'B', 16);
                $pdf->SetTextColor(26, 26, 46);
                $pdf->SetXY(20, $y);
                $pdf->Cell(170, 10, $shopName, 0, 1, 'C');
                $y += 14;
            }

            // ── Filet or ─────────────────────────────────────────
            $pdf->SetDrawColor(179, 139, 89);
            $pdf->SetLineWidth(0.5);
            $pdf->Line(30, $y, 180, $y);
            $y += 6;

            // ── Titre ─────────────────────────────────────────────
            $this->pdfSetFont($pdf, $fontSerif, 'B', 22);
            $pdf->SetTextColor(26, 26, 46);
            $pdf->SetXY(20, $y);
            $pdf->Cell(170, 10, mb_strtoupper($title), 0, 1, 'C');
            $y += 12;

            // ── Sous-titre ────────────────────────────────────────
            $this->pdfSetFont($pdf, $fontSerif, 'I', 11);
            $pdf->SetTextColor(100, 80, 40);
            $pdf->SetXY(20, $y);
            $pdf->Cell(170, 8, $subtitle, 0, 1, 'C');
            $y += 14;

            // ── Tableau des informations ──────────────────────────
            $fields = [
                $engine->get('certificate_email', 'certificate_pdf_label_product', $lang)       => $productName,
                $engine->get('certificate_email', 'certificate_pdf_label_serial', $lang)         => $serial,
                $engine->get('certificate_email', 'certificate_pdf_label_order_date', $lang)     => $dateStr,
                $engine->get('certificate_email', 'certificate_pdf_label_certified_date', $lang) => $issuedStr,
                $engine->get('certificate_email', 'certificate_pdf_label_owner', $lang)          => $customerName,
                $engine->get('certificate_email', 'certificate_pdf_label_order', $lang)          => '#' . (int) $order->id,
            ];

            foreach ($fields as $label => $value) {
                $this->pdfSetFont($pdf, $fontSans, 'B', 9);
                $pdf->SetTextColor(130, 100, 50);
                $pdf->SetXY(25, $y);
                $pdf->Cell(50, 7, mb_strtoupper($label), 0, 0, 'L');

                $this->pdfSetFont($pdf, $fontSans, '', 10);
                $pdf->SetTextColor(26, 26, 46);
                $pdf->SetXY(75, $y);
                $pdf->Cell(115, 7, $value, 0, 1, 'L');

                // Filet léger sous chaque ligne
                $pdf->SetDrawColor(220, 200, 170);
                $pdf->SetLineWidth(0.2);
                $pdf->Line(25, $y + 7, 185, $y + 7);
                $y += 9;
            }

            $y += 6;

            // ── Note de l'artisan ─────────────────────────────────
            if ($artisanNote !== '') {
                $this->pdfSetFont($pdf, $fontSerif, 'I', 10);
                $pdf->SetTextColor(80, 60, 30);
                $pdf->SetXY(25, $y);
                $pdf->MultiCell(160, 6, '"' . $artisanNote . '"', 0, 'C');
                $y = $pdf->GetY() + 6;
            }

            // ── Corps du texte ────────────────────────────────────
            $this->pdfSetFont($pdf, $fontSans, '', 9);
            $pdf->SetTextColor(100, 100, 100);
            $pdf->SetXY(25, $y);
            $pdf->MultiCell(160, 5, $bodyText, 0, 'C');
            $y = $pdf->GetY() + 10;

            // ── QR code (optionnel) ───────────────────────────────
            if ($qrEnabled) {
                // cert_qr_url n'est validée qu'avec Validate::isUrl() + préfixe
                // https:// (BO) — rien n'empêche un marchand d'y saisir une URL
                // contenant déjà une query string (ex. https://x.fr/verify?ref=y).
                // Concaténer '?cert=' dans ce cas produit une URL invalide
                // ('...?ref=y?cert=...') : le QR de TOUS les certificats émis
                // avec cette config pointe vers un lien cassé.
                $qrSeparator = strpos($qrBaseUrl, '?') !== false ? '&' : '?';
                $qrUrl = rtrim($qrBaseUrl, '/') . $qrSeparator . 'cert=' . urlencode($serial);
                $pdf->write2DBarcode($qrUrl, 'QRCODE,H', 25, $y, 28, 28);

                $this->pdfSetFont($pdf, $fontSans, '', 7);
                $pdf->SetTextColor(150, 150, 150);
                $pdf->SetXY(55, $y + 8);
                $pdf->Cell(130, 5, $engine->get('certificate_email', 'certificate_pdf_qr_hint', $lang), 0, 0, 'L');
                $pdf->SetXY(55, $y + 14);
                $pdf->Cell(130, 5, $qrUrl, 0, 0, 'L');
                $y += 32;
            }

            // ── Signature ─────────────────────────────────────────
            $pdf->SetDrawColor(179, 139, 89);
            $pdf->SetLineWidth(0.5);
            $pdf->Line(30, $y, 180, $y);
            $y += 4;

            if ($sigPath !== '') {
                $pdf->Image($sigPath, 80, $y, 50, 0);
                $y += 22;
            }

            $this->pdfSetFont($pdf, $fontSans, 'I', 9);
            $pdf->SetTextColor(100, 80, 40);
            $pdf->SetXY(20, $y);
            $pdf->Cell(170, 6, strtr($engine->get('certificate_email', 'certificate_pdf_signature', $lang), $pdfVars), 0, 1, 'C');

            // ── Pied de page ──────────────────────────────────────
            $this->pdfSetFont($pdf, $fontSans, '', 7);
            $pdf->SetTextColor(180, 160, 130);
            $pdf->SetXY(20, 270);
            $pdf->Cell(170, 5, strtr($engine->get('certificate_email', 'certificate_pdf_footer', $lang), $pdfVars), 0, 0, 'C');

            $pdfContent = $pdf->Output('certificate_' . $serial . '.pdf', 'S');

        } catch (\Throwable $e) {
            return ['error' => AdminTranslator::tVars('msg.certificate_pdf_error', ['error' => $e->getMessage()])];
        }

        // Sauvegarde optionnelle sur disque
        $dir  = _PS_MODULE_DIR_ . 'neria/certificates/';
        $file = 'cert_' . preg_replace('/[^a-z0-9_\-]/i', '_', $serial) . '.pdf';
        $path = '';
        if (!is_dir($dir)) {
            @mkdir($dir, 0755, true);
        }
        if (is_dir($dir)) {
            // file_put_contents() peut échouer silencieusement (disque plein,
            // permissions, quota) — sans vérifier son retour, $path était
            // enregistré en DB même si le fichier n'existait pas ou était
            // tronqué, sans que rien ne le détecte ni ne le journalise.
            $written = @file_put_contents($dir . $file, $pdfContent);
            if ($written !== false && $written === strlen($pdfContent)) {
                $path = 'certificates/' . $file;
            } elseif (class_exists('WatchdogManager')) {
                (new \WatchdogManager($this->module))->warning(
                    'Échec d\'écriture du PDF certificat sur disque : ' . $dir . $file,
                    '', 'CertificateManager'
                );
            }
        }

        // Même assainissement que $file ci-dessus (whitelist alphanumérique)
        // — auparavant $serial brut était utilisé ici, sans assainissement,
        // alors qu'il est saisi librement par l'admin en BO (cert_serial).
        // Un guillemet dans le numéro de série pouvait rompre l'attribut
        // filename="..." de l'en-tête Content-Disposition au téléchargement
        // (neria.php, action cert_download).
        $safeSerial = preg_replace('/[^a-z0-9_\-]/i', '_', $serial);

        return ['content' => $pdfContent, 'path' => $path, 'filename' => 'certificat_' . $safeSerial . '.pdf'];
    }

    // ============================================================
    // ENVOI EMAIL
    // ============================================================

    /**
     * Envoie le certificat par email via le pipeline Neria standard
     * (Mail::Send → hook actionEmailSendBefore → EmailRenderer), comme tous
     * les autres templates du module — design, traduction 19 langues et
     * détection automatique de la langue du client comprises. Auparavant
     * cet envoi utilisait mail() natif avec un HTML entièrement codé en dur
     * en français : un client non-francophone recevait donc son certificat
     * (email de luxe, contenu officiel) intégralement en français, quelle
     * que soit sa langue configurée — jamais rendu via le template
     * certificate_email (ni {neria_trad}, ni auto-détection de langue).
     * Mail::Send() supporte nativement les pièces jointes (paramètre
     * $fileAttachment), donc le PDF reste attaché sans MIME manuel.
     */
    private function sendCertificateEmail(
        string $to,
        string $customerName,
        string $productName,
        string $serial,
        string $pdfContent,
        \Order $order,
        int    $idLang
    ): string {
        if (!\Validate::isEmail($to)) {
            return AdminTranslator::t('msg.certificate_recipient_invalid');
        }

        // id_shop DE LA COMMANDE, pas Context::getContext()->shop (contexte
        // BO de l'employé qui déclenche l'émission) — même correctif que
        // l'INSERT en base dans issue() ci-dessus : un employé en contexte
        // "toutes les boutiques" (ou dont le contexte BO courant diffère de
        // la boutique de la commande) émettant un certificat pour une
        // commande d'une AUTRE boutique envoyait sinon l'email avec la
        // config SMTP/expéditeur de la MAUVAISE boutique (Mail::Send() lit
        // $idShop pour résoudre la config d'envoi par boutique).
        $idShop   = (int) $order->id_shop;
        $filename = 'certificat_' . preg_replace('/[^a-z0-9_\-]/i', '_', $serial) . '.pdf';

        // getShopDomainSsl() est lié au CONTEXTE courant, pas à un id_shop
        // passé en paramètre (contrairement à Mail::Send() ci-dessous) —
        // bascule temporaire vers la vraie boutique de la commande, le temps
        // de résoudre {shop_url}, même pattern que BehavioralCronManager.
        // Sans ça, {shop_url} pointait vers le domaine du contexte BO de
        // l'employé au lieu de celui de la boutique réelle de la commande.
        $originalShop = \Context::getContext()->shop;
        if ((int) $originalShop->id !== $idShop) {
            \Context::getContext()->shop = new \Shop($idShop);
        }
        $shopUrl = \Tools::getShopDomainSsl(true, true);
        \Context::getContext()->shop = $originalShop;

        $vars = [
            '{firstname}'      => $customerName,
            '{customer_name}'  => $customerName,
            '{product_name}'   => $productName,
            '{serial_number}'  => $serial,
            '{id_order}'       => (int) $order->id,
            '{order_name}'     => $order->reference,
            // Configuration::get(..., $idShop) : round 106, même piège que
            // {shop_url} juste au-dessus (déjà scopé via la bascule
            // temporaire de Context::shop) — {shop_name}, lui, était résolu
            // via le contexte non scopé, restauré à $originalShop juste
            // avant cette ligne.
            '{shop_name}'      => (string) \Configuration::get('PS_SHOP_NAME', null, null, $idShop),
            '{shop_url}'       => $shopUrl,
        ];

        $sent = \Mail::Send(
            $idLang,
            'certificate_email',
            '', // sujet auto-traduit depuis greeting_main (EmailRenderer)
            $vars,
            $to,
            $customerName !== '' ? $customerName : null,
            null,
            null,
            ['content' => $pdfContent, 'name' => $filename, 'mime' => 'application/pdf'],
            null,
            _PS_MODULE_DIR_ . 'neria/mails/',
            false,
            $idShop
        );

        return $sent ? '' : AdminTranslator::t('msg.certificate_mail_send_failed');
    }

    // ============================================================
    // LISTE & STATS
    // ============================================================

    public function getAll(int $limit = 100, int $offset = 0): array
    {
        return $this->db->executeS(
            'SELECT c.*, o.reference AS order_ref
             FROM `' . _DB_PREFIX_ . self::TABLE . '` c
             LEFT JOIN `' . _DB_PREFIX_ . 'orders` o ON o.`id_order` = c.`id_order`
             WHERE c.`id_shop` = ' . $this->idShop . '
             ORDER BY c.`date_issued` DESC
             LIMIT ' . (int) $limit . ' OFFSET ' . (int) $offset
        ) ?: [];
    }

    public function countAll(): int
    {
        return (int) $this->db->getValue(
            'SELECT COUNT(*) FROM `' . _DB_PREFIX_ . self::TABLE . '`
             WHERE `id_shop` = ' . $this->idShop
        );
    }

    public function getByOrder(int $idOrder): array
    {
        // Pas de filtre `id_shop` = $this->idShop (contexte BO courant de
        // l'employé) : appelé depuis hookDisplayAdminOrderMainBottom, dont
        // le contexte de boutique en tête de BO peut différer de celle de
        // LA COMMANDE affichée (cas normal en multi-boutique). Avec ce
        // filtre, un certificat émis pour la commande — enregistré sous
        // `id_order` DE LA COMMANDE (round précédent, voir issue()) —
        // redevenait invisible sur la fiche commande elle-même dès que le
        // contexte BO différait, risquant une réémission en double.
        // id_order est déjà une clé globalement unique en multi-boutique
        // PrestaShop : filtrer dessus suffit à scoper la requête à la
        // bonne commande.
        return $this->db->executeS(
            'SELECT * FROM `' . _DB_PREFIX_ . self::TABLE . '`
             WHERE `id_order` = ' . $idOrder . '
             ORDER BY `date_issued` DESC'
        ) ?: [];
    }

    /**
     * KPIs pour l'onglet Certificats : total émis, taux d'envoi email,
     * tendance vs mois précédent, top 5 produits certifiés.
     */
    public function getStats(): array
    {
        $table = _DB_PREFIX_ . self::TABLE;

        $total   = (int) $this->db->getValue(
            "SELECT COUNT(*) FROM `{$table}` WHERE `id_shop` = {$this->idShop}"
        );
        $emailed = (int) $this->db->getValue(
            "SELECT COUNT(*) FROM `{$table}` WHERE `id_shop` = {$this->idShop} AND `emailed` = 1"
        );
        $thisMonth = (int) $this->db->getValue(
            "SELECT COUNT(*) FROM `{$table}`
             WHERE `id_shop` = {$this->idShop}
               AND `date_issued` >= DATE_FORMAT(NOW(), '%Y-%m-01')"
        );
        $lastMonth = (int) $this->db->getValue(
            "SELECT COUNT(*) FROM `{$table}`
             WHERE `id_shop` = {$this->idShop}
               AND `date_issued` >= DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 1 MONTH), '%Y-%m-01')
               AND `date_issued` <  DATE_FORMAT(NOW(), '%Y-%m-01')"
        );
        // Round 120 : $lastMonthComparable, dédié à trend_pct — $thisMonth
        // ne couvre que le 1er du mois à AUJOURD'HUI (fenêtre partielle),
        // alors que $lastMonth (affiché tel quel dans 'last_month') couvre
        // le mois précédent ENTIER. Comparer $thisMonth à $lastMonth
        // directement (comme trend_pct le faisait) revient à comparer des
        // fenêtres de durées différentes — même famille de bug que rounds
        // 117/118. En tout début de mois, trend_pct affichait une chute
        // artificielle massive (ex. -74% le 8 août avec un rythme
        // d'émission pourtant stable), et une hausse trompeuse en toute fin
        // de mois. $lastMonthComparable borne le mois précédent au MÊME
        // nombre de jours écoulés que $thisMonth.
        $lastMonthComparable = (int) $this->db->getValue(
            "SELECT COUNT(*) FROM `{$table}`
             WHERE `id_shop` = {$this->idShop}
               AND `date_issued` >= DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 1 MONTH), '%Y-%m-01')
               AND `date_issued` <  DATE_ADD(DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 1 MONTH), '%Y-%m-01'), INTERVAL DAY(NOW()) DAY)"
        );
        $topProducts = $this->db->executeS(
            "SELECT `product_name`, COUNT(*) AS cnt
             FROM `{$table}`
             WHERE `id_shop` = {$this->idShop}
             GROUP BY `product_name`
             ORDER BY cnt DESC
             LIMIT 5"
        ) ?: [];

        return [
            'total'        => $total,
            'emailed'      => $emailed,
            'email_rate'   => $total > 0 ? round($emailed / $total * 100, 1) : 0.0,
            'this_month'   => $thisMonth,
            'last_month'   => $lastMonth,
            'trend_pct'    => $lastMonthComparable > 0
                ? round((($thisMonth - $lastMonthComparable) / $lastMonthComparable) * 100, 1)
                : ($thisMonth > 0 ? 100.0 : 0.0),
            'top_products' => $topProducts,
        ];
    }

    public function delete(int $idCertificate): void
    {
        $row = $this->db->getRow(
            'SELECT `pdf_path` FROM `' . _DB_PREFIX_ . self::TABLE . '`
             WHERE `id_certificate` = ' . $idCertificate . '
               AND `id_shop` = ' . $this->idShop
        );
        if (!$row) {
            return;
        }
        if ($row['pdf_path']) {
            $file = _PS_MODULE_DIR_ . 'neria/' . $row['pdf_path'];
            if (file_exists($file)) {
                @unlink($file);
            }
        }
        $this->db->delete(self::TABLE, '`id_certificate` = ' . $idCertificate . ' AND `id_shop` = ' . $this->idShop);
    }

    // ============================================================
    // HELPERS
    // ============================================================

    private function generateSerial(int $offset = 0): string
    {
        $prefix = (string) \Configuration::get(self::CFG_SERIAL_PREFIX) ?: 'CERT';
        $year   = date('Y');
        // Volontairement NON scopé par id_shop : serial_number porte une
        // contrainte UNIQUE GLOBALE (toutes boutiques confondues, cf.
        // createTable()) que serialExists() vérifie elle aussi sans filtre
        // id_shop. Une numérotation scopée par boutique faisait
        // naturellement converger deux boutiques vers les mêmes suffixes
        // (chacune recommençant à 000001) — collision quasi systématique
        // dès la 2e boutique, provoquant un échec d'émission récurrent
        // (les 5 tentatives avec offset croissant de issue() se heurtaient
        // toutes à des numéros déjà pris par la boutique la plus active).
        // Basé sur le MAX global, la suite ne collisionne jamais entre
        // boutiques — seul le "chaque boutique recommence à 1" cosmétique
        // est perdu, au profit d'une émission qui ne bloque plus jamais.
        //
        // Le compteur AUTO_INCREMENT réel de la table (information_schema),
        // pas MAX(id_certificate) : ce dernier RÉTROGRADE quand la ligne au
        // plus grand id_certificate est supprimée (delete(), action BO
        // "cert_delete"), alors qu'InnoDB ne recycle JAMAIS un id
        // AUTO_INCREMENT déjà consommé après un DELETE (contrairement à un
        // TRUNCATE). Avec MAX(id_certificate), supprimer le certificat le
        // plus récent faisait régénérer exactement le même numéro de série
        // pour la prochaine émission — deux certificats différents (clients,
        // produits, dates distincts) avec un serial_number identique,
        // vidant de son sens la fonction de vérification d'authenticité.
        // ANALYZE TABLE force InnoDB à rafraîchir ses statistiques
        // persistantes avant la lecture — sans ça, information_schema.TABLES
        // .AUTO_INCREMENT peut renvoyer une valeur mise en cache par MySQL
        // (system variable information_schema_stats_expiry, 24h par défaut),
        // pouvant retomber sous un id_certificate déjà consommé et
        // reproduire le bug d'origine sous une autre forme. Coût négligeable
        // : appelé uniquement à l'émission d'un certificat, jamais en boucle
        // sur un gros volume.
        $this->db->execute('ANALYZE TABLE `' . _DB_PREFIX_ . self::TABLE . '`');
        $nextAutoIncrement = (int) $this->db->getValue(
            'SELECT `AUTO_INCREMENT` FROM `information_schema`.`TABLES`
             WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = \'' . _DB_PREFIX_ . self::TABLE . '\''
        );
        // Repli sur MAX+1 si l'introspection échoue (permissions restreintes
        // sur certains hébergements mutualisés) — comportement identique à
        // avant ce correctif, pas une régression pour cet environnement.
        $last = $nextAutoIncrement > 0
            ? $nextAutoIncrement - 1
            : (int) $this->db->getValue('SELECT MAX(`id_certificate`) FROM `' . _DB_PREFIX_ . self::TABLE . '`');
        return strtoupper($prefix) . '-' . $year . '-' . str_pad($last + 1 + $offset, 6, '0', STR_PAD_LEFT);
    }

    private function serialExists(string $serial): bool
    {
        return (bool) $this->db->getValue(
            'SELECT COUNT(*) FROM `' . _DB_PREFIX_ . self::TABLE . '`
             WHERE `serial_number` = \'' . pSQL($serial) . '\''
        );
    }

    public static function createTable(): bool
    {
        return \Db::getInstance()->execute(
            'CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . self::TABLE . '` (
                `id_certificate`  INT(11)      NOT NULL AUTO_INCREMENT,
                `id_shop`         INT(11)      NOT NULL DEFAULT 1,
                `id_customer`     INT UNSIGNED NOT NULL DEFAULT 0,
                `id_order`        INT(11)      NOT NULL,
                `id_product`      INT(11)      NOT NULL,
                `id_order_detail` INT(11)      NOT NULL DEFAULT 0,
                `serial_number`   VARCHAR(100) NOT NULL,
                `customer_name`   VARCHAR(255) NOT NULL DEFAULT "",
                `product_name`    VARCHAR(255) NOT NULL DEFAULT "",
                `artisan_note`    TEXT         DEFAULT NULL,
                `pdf_path`        VARCHAR(500) DEFAULT NULL,
                `emailed`         TINYINT(1)   NOT NULL DEFAULT 0,
                `date_issued`     DATETIME     NOT NULL,
                `date_add`        DATETIME     NOT NULL,
                PRIMARY KEY (`id_certificate`),
                UNIQUE KEY `uq_serial` (`serial_number`),
                KEY `idx_order`    (`id_order`),
                KEY `idx_shop`     (`id_shop`),
                KEY `idx_customer` (`id_customer`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'
        );
    }
}
